signalfx/page-imports

- CollectD/Page_Mesos.json
Mesos Clusters, Mesos Cluster, Mesos Master, and Mesos Slave dashboards.
> Add Mesos dashboards

- CollectD/Page_CollectD.json
- CollectD/Page_CollectD_SFX.json
And add a SFX plugin version.
collectd: Appears when collectd is used.
collectdsfx: Appears when cpu.utilization is available. 
Users of the sfx plugin will see two dashboards.
> Change collectd discovery

- CollectD/Page_Varnish.json
According to Jack via Harnit, the way we calculate hit rate in these
dashboards was overcomplicated and/or wrong. hits/(hits + misses) will
suffice.
> Changing hit rate calculation.

- AWS/Page_AWS SQS.json
Preview in app: https://app.signalfx.com/#/dashboard/Cryoti2AgFM <-- SFDemo
> Added ApproximateAgeOfOldestMessage.

- CollectD/Page_CollectD_SFX.json
Changed- 
collectd (a): Total memory
collectd: Memory
Preview: https://app.signalfx.com/#/dashboard/CsAaozqAgAA <-- dgriff org
> Memory charts needed customized legends.

- Windows/Page_Windows IIS.json
Not sure how images will work with this
> Added Windows IIS dashboards as SD dashboards

- Windows/Page_Windows IIS.json
> Remove default values for required dashboard variables.

- CollectD/Page_CollectD_SFX.json
- Telegraf/Page_Infrastructure_Telegraf.json
* Explicitly filter out "agents" on collectd (a)
* Prevent collectd and collectd (a) from being added to telegraf hosts
* Add telegraf dashboards
* Remove garbage filters on individual collectd charts such as overridden host filters for specific hosts
> add infrastructure dashboards for telegraf

- PivotalCloudFoundry/Page_Cloud Foundry.json
Tested by importing into lab. Only the org with PCF metrics got the dashboard,
the others didn't.
> Add PCF dashboards

- CollectD/Page_NGINX_Plus.json
Added Page_NGINX_Plus.json for NGINX Plus integration
> INT-106: NGINX Plus Integration Dashboards

- Kubernetes/Page_Kubernetes.json
> Using ICE units on K8s Memory Chart

- AWS/Page_AWS Redshift.json
changed marshallScope origin to point to '2', a dashboard group, instead of '3', a dashboard.
> add correct version of AWS Redshift dashboard

- CollectD/Page_Etcd.json
Removed additional info list charts to avoid cluttering
> Reduce information on list charts

- AWS/Page_DynamoDB.json
marshallScope maps to mashallID of type "page", and namespace for dashboards are set for DynamoDB 👍
> add AWS DynamoDB default dashboard

- CollectD/Page_CouchDB.json
> Page import for CouchDB

- CollectD/Page_CouchDB.json
Update CouchDB dashboard variables
node & cluster filter required in Nodes
cluster filter required in Cluster
> Update CouchDB dashboard variables

- GCP/Page_Google Cloud Bigtable.json
chart could not be filtered on a per table basis, chart is already in the cluster dashboard
> remove invalid chart from Table page

- AWS/Page_AWS Lambda.json
For single value, list, and heatmap charts.
> Set extrapolation in Lambda dashboards

- GCP/Page_Google Cloud Spanner.json
- GCP/Page_Google Compute Engine.json
overlapping query selectors were causing issues in nav views
> update discovery selectors for spanner and compute

- CollectD/Page_Apache Solr.json
Add page import for apache solr
> Add page for apache solr

- azure/Page_Azure App Service.json
- azure/Page_Azure Batch.json
- azure/Page_Azure Event Hubs.json
- azure/Page_Azure Logic Apps.json
- azure/Page_Azure Redis Caches.json
- azure/Page_Azure SQL Server Elastic Pools.json
- azure/Page_Azure Sql Databases.json
- azure/Page_Azure Storage.json
- azure/Page_Azure VM Scale Sets.json
- azure/Page_Azure Virtual Machines.json
> add inital azure dashboards

- AWS/Page_AWS AutoScaling.json
Changes from https://github.com/signalfx/page-imports-staging/pull/115
> Update AWS AutoScaling dashboard

- Kubernetes/Page_Kubernetes.json
It now uses quota/period instead of shares.
> Fixing K8s CPU limit chart

- CollectD/Page_Kafka.json
Updated existing charts
Added new charts as per new metrics added
Added JVM dashboard
> Updated kafka dashboard with enhanced metrics

- azure/Page_Azure App Service.json
- azure/Page_Azure Functions.json
- azure/Page_Azure Storage.json
wait to merge until after page-imports-staging verification
add azure functions dashboard group
modify azure app service to use new "is_Azure_Function_" dimension
modify storage dashboard group selectors bc they were limiting azure functions
> add azure functions

- CollectD/Page_Apache_Spark_Applications.json
invalid metric name was being used in a chart
several charts were using 'A/B' as a metric and not a formula
> fix metric name in chart, fix formulas in charts

- CollectD/Page_OpenStack.json
OpenStack built-in dashboard to prod
> OpenStack built-in dashboard to prod

- CollectD/Page_Kafka.json
Remove 'clusters' chart from kafka dashboard
> Patch kafka dashboard

- CollectD/Page_Kong.json
Includes five dashboards for Kong integration.
> Add Kong dashboard group

- Kubernetes/Page_Kubernetes.json
- add K8s Nodes dashboard
- add K8s Pods dashboard
- update discovery and selector queries for navs
- update K8s clusters dashboard with more meaningful CPU% and Memory % metrics
- updated all chart titles and add suffix units where applicable
- added a couple useful charts to K8s Node
> updating k8s dashboards
